### ISSUE TITLE
I have some questions about tasty file inspectation

### ISSUE THREAD

**Issue by HalfLegend** [gzoller/scala-reflection#33]
This is just some questions, not an issue.

Question 1:
```
/** This class is needed for runtime inspection--so we can get a Reflection object to pass to unwindType
 */
class TastyInspection(clazz: Class[_]) extends Inspector:

  var inspected: RType = UnknownInfo(clazz.getName)

  // Note: Class arg to TastyInspection drives inspection, NOT tastys List.
  def inspect(using Quotes)(tastys: List[Tasty[quotes.type]]): Unit =
    import quotes.reflect._
    val tastyType = quotes.reflect.TypeRepr.typeConstructorOf(clazz)
    inspected = RType.unwindType(quotes)( tastyType, false )
```
As we could see, the tasty file is not used in this method, as is described in the note. 
What the method do is just to enter a scope where Quotes exists, is it?
That is to say, if I have a `class A` with `A.tasty`  and a `B.tasty` which has nothing to do with A.
I want to reflect the fields in A. If I give the path to B.tasty, the TastyInspection also works, and could also return the correct fields in `class A`, is it?

Questions 2:
What is the difference between TastyInspection and withQuotes?   They could both obain "Quotes" in their scope.

@gzoller 
Thank you very much for this library which helped me a lot.
I have much interest in scala reflection and macro programming, but the official reference could not explain everything such as questions above and I cound not find any better reference. I am very pleased if you could give me some suggestions

**Comment by HalfLegend** [comment]
I tested the performance of TastyInspection and withQuotes in Question 2,  and the latter one has a better performance, even 5 times better.

So I am wondering if there is any behavior difference beween the two solution?
If there is no difference, I recommand to use `withQuotes` as the default implementation

**Comment by HalfLegend** [comment]
···
        val tc = new TastyInspection(clazz)
        val tastyPathOpt = PathResolver.findPathForClass(classOf[ArrayInfo])
···
I tried to fix the path of tasty to `ArrayInfo` instead of clazz, and it is still working fine.

**Comment by gzoller** [comment]
I'm not 100% sure about your question, but I think you're wondering why sometimes Quotes exists and other times not.  It's been some time since I looked at this code... but I think the difference is this:   This library was designed to work in 2 distinct modes.  You can enable it as a compiler plug-in to get macro support (which has Quotes available).  Understanding that maybe some folks won't want to do that--they prefer a "stock" compiler--this library still works, but will parse the .tasty files.  This is much slower due to the file IO, however the actual logic is the same, so I think what you're seeing there is provision for handling the same work with/without the Quotes.

You're absolutely right about metaprogramming documentation.  It's... not super.  99% of this library was due to banging my head against a wall and the amazing Gitter support of several key members of the Scala 3 team.  In a few cases I even had to add PRs into Scala 3 itself to plug a hole or two in the Tasty handling.  I use reflection a lot, so I didn't want to crawl through compiler internals each time--wanted a higher-level abstraction like the old reflection in Scala 2, which is what this library attempts to provide.

**Comment by HalfLegend** [comment]
Thanks very much
