### ISSUE TITLE
Case Object reflection

### ISSUE THREAD

**Issue by nvollmar** [gzoller/scala-reflection#39]
I'm was testing your library as it looked like suitable replacement.
Seems that object fields are not read? Or is this an issue when not using the compiler plugin?

**Comment by pjfanning** [comment]
@nvollmar could you provide an example? I use this lib and have not seen problems with objects but maybe my use cases differ from yours.

**Comment by pjfanning** [comment]
Maybe @gzoller will have a look but one possible workaround is to use jackson-module-scala BeanIntropector.

```
println(com.fasterxml.jackson.module.scala.introspect.BeanIntrospector(TestObject.getClass).properties)
```

**Comment by gzoller** [comment]
I’ll have a look and try your example.

**Comment by gzoller** [comment]
OK, I think I understand what’s happening.  scala-relection was initially conceived as a utility liberary to support my ScalaJack serialization library after Scala 3 eliminated built-in reflection capability, so its entirely possible their may gaps in this library.  In this case, I don’t think I implemented fields in a case object, because (for serialization) I figured they’d only be used as enum values and therefore not constructed in the same way a class would be—i.e. you can’t set the val fields post compile-time anyway, so I ignore any data fields.

Let me know if the posted workaround works or not.  If not, I can probably enhance this library to reflect on the data fields but it may take some time.

**Comment by nvollmar** [comment]
Thanks for looking into it. Since this is only one small area where Scala 3 breaks, we went ahead using plain old Java Reflection for the time being.
